# Config settings
title: Simple Pages Title
author: Simple Pages Author - Me
email: site@email.me
description: Simple Pages Description

# social links
github_username: stepanhakobyan

theme: minima

header_pages:
  - second.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

